package com.limbo.practice.base.entity;

import java.util.Date;

public class SysMenu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.id
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.menu_name
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    private String menuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.menu_url
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    private String menuUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.menu_type
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    private Boolean menuType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.menu_sort
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    private Byte menuSort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.menu_description
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    private String menuDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.is_deleted
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    private Boolean isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.gmt_create
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.gmt_modified
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public SysMenu(Long id, String menuName, String menuUrl, Boolean menuType, Byte menuSort, String menuDescription, Boolean isDeleted, Date gmtCreate, Date gmtModified) {
        this.id = id;
        this.menuName = menuName;
        this.menuUrl = menuUrl;
        this.menuType = menuType;
        this.menuSort = menuSort;
        this.menuDescription = menuDescription;
        this.isDeleted = isDeleted;
        this.gmtCreate = gmtCreate;
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public SysMenu() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.id
     *
     * @return the value of sys_menu.id
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.id
     *
     * @param id the value for sys_menu.id
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.menu_name
     *
     * @return the value of sys_menu.menu_name
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.menu_name
     *
     * @param menuName the value for sys_menu.menu_name
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName == null ? null : menuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.menu_url
     *
     * @return the value of sys_menu.menu_url
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public String getMenuUrl() {
        return menuUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.menu_url
     *
     * @param menuUrl the value for sys_menu.menu_url
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public void setMenuUrl(String menuUrl) {
        this.menuUrl = menuUrl == null ? null : menuUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.menu_type
     *
     * @return the value of sys_menu.menu_type
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public Boolean getMenuType() {
        return menuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.menu_type
     *
     * @param menuType the value for sys_menu.menu_type
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public void setMenuType(Boolean menuType) {
        this.menuType = menuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.menu_sort
     *
     * @return the value of sys_menu.menu_sort
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public Byte getMenuSort() {
        return menuSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.menu_sort
     *
     * @param menuSort the value for sys_menu.menu_sort
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public void setMenuSort(Byte menuSort) {
        this.menuSort = menuSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.menu_description
     *
     * @return the value of sys_menu.menu_description
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public String getMenuDescription() {
        return menuDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.menu_description
     *
     * @param menuDescription the value for sys_menu.menu_description
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public void setMenuDescription(String menuDescription) {
        this.menuDescription = menuDescription == null ? null : menuDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.is_deleted
     *
     * @return the value of sys_menu.is_deleted
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.is_deleted
     *
     * @param isDeleted the value for sys_menu.is_deleted
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.gmt_create
     *
     * @return the value of sys_menu.gmt_create
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.gmt_create
     *
     * @param gmtCreate the value for sys_menu.gmt_create
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.gmt_modified
     *
     * @return the value of sys_menu.gmt_modified
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.gmt_modified
     *
     * @param gmtModified the value for sys_menu.gmt_modified
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}