package com.limbo.practice.base.entity;

import java.util.Date;

public class SysPermission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.id
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.permission_name
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    private String permissionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.permission_description
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    private String permissionDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.permission_url
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    private String permissionUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.permission_type
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    private Boolean permissionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.is_deleted
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    private Boolean isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.gmt_create
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.gmt_modified
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public SysPermission(Long id, String permissionName, String permissionDescription, String permissionUrl, Boolean permissionType, Boolean isDeleted, Date gmtCreate, Date gmtModified) {
        this.id = id;
        this.permissionName = permissionName;
        this.permissionDescription = permissionDescription;
        this.permissionUrl = permissionUrl;
        this.permissionType = permissionType;
        this.isDeleted = isDeleted;
        this.gmtCreate = gmtCreate;
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public SysPermission() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.id
     *
     * @return the value of sys_permission.id
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.id
     *
     * @param id the value for sys_permission.id
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.permission_name
     *
     * @return the value of sys_permission.permission_name
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public String getPermissionName() {
        return permissionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.permission_name
     *
     * @param permissionName the value for sys_permission.permission_name
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public void setPermissionName(String permissionName) {
        this.permissionName = permissionName == null ? null : permissionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.permission_description
     *
     * @return the value of sys_permission.permission_description
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public String getPermissionDescription() {
        return permissionDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.permission_description
     *
     * @param permissionDescription the value for sys_permission.permission_description
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public void setPermissionDescription(String permissionDescription) {
        this.permissionDescription = permissionDescription == null ? null : permissionDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.permission_url
     *
     * @return the value of sys_permission.permission_url
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public String getPermissionUrl() {
        return permissionUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.permission_url
     *
     * @param permissionUrl the value for sys_permission.permission_url
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public void setPermissionUrl(String permissionUrl) {
        this.permissionUrl = permissionUrl == null ? null : permissionUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.permission_type
     *
     * @return the value of sys_permission.permission_type
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public Boolean getPermissionType() {
        return permissionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.permission_type
     *
     * @param permissionType the value for sys_permission.permission_type
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public void setPermissionType(Boolean permissionType) {
        this.permissionType = permissionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.is_deleted
     *
     * @return the value of sys_permission.is_deleted
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.is_deleted
     *
     * @param isDeleted the value for sys_permission.is_deleted
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.gmt_create
     *
     * @return the value of sys_permission.gmt_create
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.gmt_create
     *
     * @param gmtCreate the value for sys_permission.gmt_create
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.gmt_modified
     *
     * @return the value of sys_permission.gmt_modified
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.gmt_modified
     *
     * @param gmtModified the value for sys_permission.gmt_modified
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}