package com.limbo.practice.base.entity;

import java.util.Date;

public class SysRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.id
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.role_name
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.role_description
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    private String roleDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.is_deleted
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    private Boolean isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.gmt_create
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.gmt_modified
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public SysRole(Long id, String roleName, String roleDescription, Boolean isDeleted, Date gmtCreate, Date gmtModified) {
        this.id = id;
        this.roleName = roleName;
        this.roleDescription = roleDescription;
        this.isDeleted = isDeleted;
        this.gmtCreate = gmtCreate;
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public SysRole() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.id
     *
     * @return the value of sys_role.id
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.id
     *
     * @param id the value for sys_role.id
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.role_name
     *
     * @return the value of sys_role.role_name
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.role_name
     *
     * @param roleName the value for sys_role.role_name
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.role_description
     *
     * @return the value of sys_role.role_description
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public String getRoleDescription() {
        return roleDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.role_description
     *
     * @param roleDescription the value for sys_role.role_description
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public void setRoleDescription(String roleDescription) {
        this.roleDescription = roleDescription == null ? null : roleDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.is_deleted
     *
     * @return the value of sys_role.is_deleted
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.is_deleted
     *
     * @param isDeleted the value for sys_role.is_deleted
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.gmt_create
     *
     * @return the value of sys_role.gmt_create
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.gmt_create
     *
     * @param gmtCreate the value for sys_role.gmt_create
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.gmt_modified
     *
     * @return the value of sys_role.gmt_modified
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.gmt_modified
     *
     * @param gmtModified the value for sys_role.gmt_modified
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}