package com.limbo.practice.base.entity;

import java.util.Date;

public class SysRoleUser extends SysRoleUserKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_user.is_deleted
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    private Boolean isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_user.gmt_create
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_user.gmt_modified
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_user
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public SysRoleUser(Long id, Long roleId, Long userId, Boolean isDeleted, Date gmtCreate, Date gmtModified) {
        super(id, roleId, userId);
        this.isDeleted = isDeleted;
        this.gmtCreate = gmtCreate;
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_user
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public SysRoleUser() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_user.is_deleted
     *
     * @return the value of sys_role_user.is_deleted
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_user.is_deleted
     *
     * @param isDeleted the value for sys_role_user.is_deleted
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_user.gmt_create
     *
     * @return the value of sys_role_user.gmt_create
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_user.gmt_create
     *
     * @param gmtCreate the value for sys_role_user.gmt_create
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_user.gmt_modified
     *
     * @return the value of sys_role_user.gmt_modified
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_user.gmt_modified
     *
     * @param gmtModified the value for sys_role_user.gmt_modified
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}