package com.limbo.practice.base.entity;

import java.util.Date;

public class SysUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.id
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.login_account
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    private String loginAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.login_pass
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    private String loginPass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.login_salt
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    private String loginSalt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_name
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_head
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    private String userHead;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_phone
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    private String userPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_email
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    private String userEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_sex
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    private Boolean userSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_type
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    private Boolean userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.login_status
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    private Boolean loginStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.last_login_time
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    private Date lastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.last_login_ip
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    private String lastLoginIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.is_locked
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    private Boolean isLocked;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.is_deleted
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    private Boolean isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.gmt_create
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.gmt_modified
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public SysUser(Long id, String loginAccount, String loginPass, String loginSalt, String userName, String userHead, String userPhone, String userEmail, Boolean userSex, Boolean userType, Boolean loginStatus, Date lastLoginTime, String lastLoginIp, Boolean isLocked, Boolean isDeleted, Date gmtCreate, Date gmtModified) {
        this.id = id;
        this.loginAccount = loginAccount;
        this.loginPass = loginPass;
        this.loginSalt = loginSalt;
        this.userName = userName;
        this.userHead = userHead;
        this.userPhone = userPhone;
        this.userEmail = userEmail;
        this.userSex = userSex;
        this.userType = userType;
        this.loginStatus = loginStatus;
        this.lastLoginTime = lastLoginTime;
        this.lastLoginIp = lastLoginIp;
        this.isLocked = isLocked;
        this.isDeleted = isDeleted;
        this.gmtCreate = gmtCreate;
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public SysUser() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.id
     *
     * @return the value of sys_user.id
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.id
     *
     * @param id the value for sys_user.id
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.login_account
     *
     * @return the value of sys_user.login_account
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public String getLoginAccount() {
        return loginAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.login_account
     *
     * @param loginAccount the value for sys_user.login_account
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public void setLoginAccount(String loginAccount) {
        this.loginAccount = loginAccount == null ? null : loginAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.login_pass
     *
     * @return the value of sys_user.login_pass
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public String getLoginPass() {
        return loginPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.login_pass
     *
     * @param loginPass the value for sys_user.login_pass
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public void setLoginPass(String loginPass) {
        this.loginPass = loginPass == null ? null : loginPass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.login_salt
     *
     * @return the value of sys_user.login_salt
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public String getLoginSalt() {
        return loginSalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.login_salt
     *
     * @param loginSalt the value for sys_user.login_salt
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public void setLoginSalt(String loginSalt) {
        this.loginSalt = loginSalt == null ? null : loginSalt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_name
     *
     * @return the value of sys_user.user_name
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_name
     *
     * @param userName the value for sys_user.user_name
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_head
     *
     * @return the value of sys_user.user_head
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public String getUserHead() {
        return userHead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_head
     *
     * @param userHead the value for sys_user.user_head
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public void setUserHead(String userHead) {
        this.userHead = userHead == null ? null : userHead.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_phone
     *
     * @return the value of sys_user.user_phone
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_phone
     *
     * @param userPhone the value for sys_user.user_phone
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_email
     *
     * @return the value of sys_user.user_email
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_email
     *
     * @param userEmail the value for sys_user.user_email
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail == null ? null : userEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_sex
     *
     * @return the value of sys_user.user_sex
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public Boolean getUserSex() {
        return userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_sex
     *
     * @param userSex the value for sys_user.user_sex
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public void setUserSex(Boolean userSex) {
        this.userSex = userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_type
     *
     * @return the value of sys_user.user_type
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public Boolean getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_type
     *
     * @param userType the value for sys_user.user_type
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public void setUserType(Boolean userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.login_status
     *
     * @return the value of sys_user.login_status
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public Boolean getLoginStatus() {
        return loginStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.login_status
     *
     * @param loginStatus the value for sys_user.login_status
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public void setLoginStatus(Boolean loginStatus) {
        this.loginStatus = loginStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.last_login_time
     *
     * @return the value of sys_user.last_login_time
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.last_login_time
     *
     * @param lastLoginTime the value for sys_user.last_login_time
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.last_login_ip
     *
     * @return the value of sys_user.last_login_ip
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public String getLastLoginIp() {
        return lastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.last_login_ip
     *
     * @param lastLoginIp the value for sys_user.last_login_ip
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public void setLastLoginIp(String lastLoginIp) {
        this.lastLoginIp = lastLoginIp == null ? null : lastLoginIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.is_locked
     *
     * @return the value of sys_user.is_locked
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public Boolean getIsLocked() {
        return isLocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.is_locked
     *
     * @param isLocked the value for sys_user.is_locked
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public void setIsLocked(Boolean isLocked) {
        this.isLocked = isLocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.is_deleted
     *
     * @return the value of sys_user.is_deleted
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.is_deleted
     *
     * @param isDeleted the value for sys_user.is_deleted
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.gmt_create
     *
     * @return the value of sys_user.gmt_create
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.gmt_create
     *
     * @param gmtCreate the value for sys_user.gmt_create
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.gmt_modified
     *
     * @return the value of sys_user.gmt_modified
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.gmt_modified
     *
     * @param gmtModified the value for sys_user.gmt_modified
     *
     * @mbggenerated Wed Jun 03 22:27:47 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}